// Autogenerated types for CCI
export type Scope = "file" | "package" | "repo" | "api" | "db" | "project";

export interface Finding {
  kind: string;
  scope: Scope;
  file?: string;
  line?: number;
  context?: string;
  left?: string;
  right?: string;
  message?: string;
  meta?: Record<string, unknown>;
}

export interface FileStat {
  path: string; // absolute
  relpath: string; // relative to workspace root
  lines: number;
  nonBlankLines: number;
  hash: string; // sha256
}

export interface FindingsPayload {
  meta: { root: string; git_sha?: string; workspaceId?: string };
  config?: Partial<CciConfig>;
  fileStats: FileStat[];
  findings: Finding[];
}

export interface FindingsReport {
  meta: { id: string; timestamp: string; kiloc: number; total_weight: number; cdx: number; cci: number };
  findings: Array<Finding & { appliedWeight?: number }>;
}

export interface CciConfig {
  backendUrl: string;
  authToken?: string;
  sendFullFiles: boolean;
  maxPayloadBytes: number;
  ignorePatterns: string[];
  timeoutMs: number;
  externalHeuristicsPath?: string;
  offlineMode?: boolean;
  heuristicFileMap?: Record<string, string[]>;
  defaultHeuristicExtensions?: string[];
  heuristicScopeMap?: Record<string, "file" | "package" | "repo">;
  fileTimeoutMs?: number;
  batchTimeoutMs?: number;
  enforcePythonOnly?: boolean;
  heavyHeuristicsDisabled?: boolean;
  maxFiles?: number;
}

export interface HeuristicContext {
  root: string;
  config: CciConfig;
  readFile(relpath: string): Promise<string>;
  fileStat(relpath: string): Promise<FileStat | undefined>;
  // helpers for package/repo-level heuristics
  getImportGraph?: () => Promise<{ nodes: string[]; edges: Array<{ from: string; to: string }> }>;
  findOpenApiSpecs?: () => Promise<Array<{ uri: { fsPath: string }; rel: string }>>;
  loadOpenApi?: (uri: { fsPath: string }) => Promise<any>;
}

export interface Heuristic {
  id: string;
  scope: Scope;
  run(ctx: HeuristicContext, input: { file?: string; content?: string }): Promise<Finding[]>;
  finalize?: (ctx: HeuristicContext, allFindings: Finding[]) => Promise<Finding[]>;
  extensions?: string[];
}


